
= Holybro Telemetry V3 Test
Johannes Hanuja <joha1003@stud.hs-kl.de>
:lang: de
:toc: left
:toc-title: Content
:toclevels: 5
:numbered:
:sectnumlevels: 5
:src_numbered: 
:icons: font
:figure-caption: Figure
:keywords: asciidoctor
:description: Holybro Telemetry V3 Test
:title: Holybro Telemetry V3 Test
:sectanchors:
:sectlinks:
:experimental:
:copyright: Wilhelm Meier
:duration: 90
:coderay-css: style
:source-highlighter: pygments
:pygments-css: class
:status:
:menu:
:navigation:
:split:
:goto:
:blank:
:deckjs_theme: swiss
:showtitle:
:docinfo1:
:stem:
:deckjs_transition: horizontal-slide
//:stylesdir: ./css
//:stylesheet: wm2.css
//:scriptsdir: ./js
:customcss: css/deckjs.css 
:revealjs_theme: beige
:revealjs_slidenumber: true
// for attributes in link:[] macro like link:xxx[window="_blank"]
:linkattrs:

:srcbase: ../src
:extractordir: .extractor


== Versuchsbeschreibung

Das Funkmodul Sik Telemetry V3 der Firma Holybro soll laut Datenblatt Entfernungen von über 300 Metern schaffen und das Senden von Paketen mit einer konstanten Datenrate garantieren. Es beinhaltet einen Buffer von 2048 kbyte, zudem ist die Sendegeschwindigkeit parametrierbar (Standart: 64kbit/s). In dieser Versuchsreihe soll die Baudrate gefunden werden mit der eine konstante Datenrate garantiert werden kann, ohne hierbei Paketverluste zu erleiden. Hierzu soll letzendlich herausgefunden werden, wann der interne Buffer des Funkmoduls überläuft. Desweiteren soll das Verhalten des Funkmoduls über größere Entfernungen überprüft werden. 

== Versuchshardware

Zur Versuchsdurchführung werden zwei der Funkmodems vewendet. Eines ist mit dem Computer über die serielle Schnittstelle verbunden. Beim zweiten Funkmodul wurden RX und TX Pin miteinander verbunden, sodass empfangene Pakete umgehend zurückgesendet werden. 

== Testprogramme

Das Testen des Funkmoduls geschieht mit Hilfe von 2 Programmen. Das Programm write verschickt eine Anzahl von Paketen mit einer Anzahl von Bytes. Zudem ist ein Delay zwischen den Paketen parametrierbar. Das Programm `write` hat die folgenden Kommandozeilenoptionen:  

[horizontal]
Option:: Beschreibung
`-h`, `--help`:: Hilfe
`-p`, `--packets`:: Anzahl Pakete
`-b`, `--bytes`:: Anzahl Bytes
`-d`, `--delay`:: Delay zwischen Paketen
`-c`, `--comport`:: Comport
`-f`, `--filename`:: Dateiname
`-a`, `--baudrate`:: Baudrate



Im Sourcecode werden die Bytes durch einzelne Chars realisiert und ein Paket ist eine zufällige Folge von Chars. Die Folge von chars beginnt immer mit einem großen P, sodass der Beginn einer Paketfolge detektiert werden kann. 

:srcdir: write
include::{srcbase}/{srcdir}/{extractordir}/write.cc.SendData[]


Das Programm `read` hat keine Delayoption, ansonsten sind die Kommandozeilenoptionen analog zum Programm `write`. Die empfangenen Bytes werden ausgelesen und ebenfalls in eine Datei geschrieben. 

:srcdir: read
include::{srcbase}/{srcdir}/{extractordir}/read.cc.ReadData[]


== Ändern der Baudrate des Funkmoduls

Unter Unix kann man das Tool picocom verwenden um die Baudrate des Funkmoduls zu ändern


`picocom -b 38400 /dev/ttyUSB0`

Die Baudrate muss mit der aktuell konfigurierten Baudrate des Funkmoduls übereinstimmen. Anschließend muss man
`+` `+` `+` 
eingeben um in den AT Modus zu gelangen.

Die aktuelle Konfiguration erhält man mittels des Befehls:

`ATI5`

Um die Baudrate nun auf beispielsweise 9600 zu ändern, muss man folgenden Befehl eingeben:

`ÀTS1=9`

Anschließend muss man noch die Eingaben persistieren, ansonsten gehen die 
Änderungen mit einem Reboot verloren.

`AT&W`

Nun kann man mittels `ATO` den AT Modus verlassen und nach einem Reboot sind die Änderungen verfügbar.

== Versuche
=== Versuch 1: Kontinuierliches Senden mit 9600 Baud 

Bei ersten Versuch wird 1MByte mit einer Baudrate von 9600 bit/s versendet. Die Anzahl Bytes pro Paket und die korrespondierende Anzahl von Paketen wird hierbei variiert. 

Fazit: Eine Datenrate von 9600 bit/s kann durch das Modem garantiert werden. Dies überrascht nicht, da die Übertragungsgeschwindigkeit 64000 bit/s beträgt und zudem ein Buffer von 2048 byte vorliegt.


=== Versuch 2: Kontinuierliches Senden mit mehr als 9600 baud

Bei diesem Versuch wird eine variierende Anzahl von Bytes mit verschiedenen Baudraten, die über 9600 liegen, versendet.

Fazit: Es kommt in wiederkehrenden Abständen zu Verlusten von ganzen Paketfolgen. Je höher die Baudrate ist, desto tritt der Verlust von Paketfolgen auf.


=== Versuch 3: Bufferüberlauf mit Hardware Flow Control detektieren
Um Bufferüberläufe zu erkennen, wird der CTS Pin des Funkmodems mit einem Logic Analyzer verbunden. 

Fazit:
Die Pufferüberläufe werden durch den Analyzer angezeigt. Anhand einer Zeitmessung kann verifiziert werden, dass der Buffer tatsächlich 2048 Byte beträgt. 


=== Versuch 4: Mavlink Pakete versenden
Laut Dokumentation versendet das Modem selbstständig RADIO_STATUS Pakete, um die Auslastung des Puffers mitzuteilen. Dies ist allerdings nur der Fall,
wenn Mavlink Paket versendet werden. Zunächst muss über den At Command ATS6 das Mavlink Flag auf 1 gesetzt werden. Desweiteren werden die RADIO_STATUS Pakete nur in den Datenstrom inkludiert, wenn Heartbeat Pakete versendet werden. Es gibt zahlreiche Libraries, um Mavlink Pakete zu versenden.
In diesem Versuch wird die Javascript Library node-mavlink verwendet, um Mavlink Pakete zu versenden und zu empfangen. Das Programm befindet sich im Ordner js.

Fazit: In der Tat werden RADIO_STATUS Pakete in den Datenstrom inkludiert, wenn Heartbeat Pakete versendet werden.

